name: SonarQube Scan

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build and analyze with Maven
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: mvn clean verify sonar:sonar -Dsonar.projectKey=train-ticket-reservation -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_TOKEN
