name: ci/cd pipeline to deploy to tomcat

on: 
  push:
    branches: master  #runs pipeline only when pushing to master branch
jobs:
   build-deploy:
     runs-on: ubuntu-latest
     
     steps:
           # checkout repo
           - name: checkout code
             uses: actions/checkout@v3
         
           # set-up java
           - name: set-up jdk
             uses: actions/setup-java@v3
             with:
               distribution: 'temurin'
               java-version: '11'
          
           - name: validate with maven
             run: mvn validate
              
           - name: compile with maven
             run: mvn compile
          
           - name: test with maven
             run: mvn test
             
           # build with maven(update)
           - name: package with maven
             run: mvn clean package
  
           - name: verify WAR file
             run: ls -lh target/
             
           - name: check tomcat connection
             run: |
                 curl --fail --anyauth -u "${{ secrets.TOMCAT_USER }}:${{ secrets.TOMCAT_PASSWORD }}" \
                 "http://${{ secrets.TOMCAT_HOST }}:8080/manager/text/list"
          # Deploy to Tomcat
           - name: Deploy to Tomcat
             run: |
               curl -v -u ${{ secrets.TOMCAT_USER }}:${{ secrets.TOMCAT_PASSWORD }} \
                -T MyWebApp/target/MyWebApp.war \
                  "http://${{ secrets.TOMCAT_HOST }}/manager/text/deploy?path=/.war&update=true"
