name: Build a WAR file using Maven and Deploy Java App to Tomcat running in AWS EC2

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Build with Maven
      run: mvn clean install

    - name: Deploy to Tomcat
      run: |
        curl -v -u ${{ secrets.TOMCAT_USER }}:${{ secrets.TOMCAT_PASSWORD }} \
        -T target/TrainBook-1.0.0-SNAPSHOT.war \
        "http://${{ secrets.TOMCAT_HOST }}/manager/text/deploy?path=/TrainBook-1.0.0-SNAPSHOT.war&update=true"
        
    - name: Deploy to Tomcat
      run: |
        curl -v -u ${{ secrets.TOMCAT_USER1 }}:${{ secrets.TOMCAT_PASSWORD1 }} \
        -T target/TrainBook-1.0.0-SNAPSHOT.war \
        "http://${{ secrets.TOMCAT_HOST1 }}/manager/text/deploy?path=/TrainBook-1.0.0-SNAPSHOT.war&update=true"
        
    - name: Deploy to Tomcat
      run: |
        curl -v -u ${{ secrets.TOMCAT_USER2 }}:${{ secrets.TOMCAT_PASSWORD2 }} \
        -T target/TrainBook-1.0.0-SNAPSHOT.war \
        "http://${{ secrets.TOMCAT_HOST2 }}/manager/text/deploy?path=/TrainBook-1.0.0-SNAPSHOT.war&update=true"
        
    - name: Deploy to Tomcat
      run: |
        curl -v -u ${{ secrets.TOMCAT_USER3 }}:${{ secrets.TOMCAT_PASSWORD3 }} \
        -T target/TrainBook-1.0.0-SNAPSHOT.war \
        "http://${{ secrets.TOMCAT_HOST3 }}/manager/text/deploy?path=/TrainBook-1.0.0-SNAPSHOT.war&update=true"
